### ISSUE TITLE
TFIDF文本相似度全局搜索算法疑惑

### ISSUE THREAD

**Issue by BERYLSHEEP** [haodong-liu/-#1]
您好！在查看您的代码中，似乎没有找到具体的TFIDF文本相似度全局搜索算法的实现。所以有部分疑虑，请问，您提到的用0.4~0.5的余弦相似度好像没有在评价函数S2中出现，那这个余弦相似度是在寻找匹配商品过程中作为一个评判标准if: else: 去处理嘛？ @haodong-liu

**Comment by haodong-liu** [comment]
抱歉，那一部分的代码我当时没有上传，目前似乎找不到了




            
            
                
                    
                            
                                
                            
                            
                                761767803
                            
                    
                        
                            
                                    邮箱：761767803@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2019年05月03日 10:19，Beryl 写道： Closed #1.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/haodong-liu/Tianchi_recommender_System_of_taobao_clothes","title":"haodong-liu/Tianchi_recommender_System_of_taobao_clothes","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/haodong-liu/Tianchi_recommender_System_of_taobao_clothes"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #1."}],"action":{"name":"View Issue","url":"https://github.com/haodong-liu/Tianchi_recommender_System_of_taobao_clothes/issues/1#event-2316143059"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/haodong-liu/Tianchi_recommender_System_of_taobao_clothes/issues/1#event-2316143059",
"url": "https://github.com/haodong-liu/Tianchi_recommender_System_of_taobao_clothes/issues/1#event-2316143059",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
